// Generated by https://quicktype.io

export interface Job {
    id:                number;
    title:             string;
    description:       string;
    startDate:         string;
    numberOfPositions: number;
}
